version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: h2
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: wp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: filip123
    ports:
      - "5433:5432"
