version: '2'
services:
  h2:
    container_name: 'h2'
    hostname: 'h2'
    image: 1000kit/h2
    ports:
      - "8081:8081"
      - "1521:1521"
    volumes:
      - h2-data:/opt/h2-data

  app:
    container_name: 'spring-app'
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"  # Adjust this port as needed
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "kiii-project-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - h2

volumes:
  h2-data:
